# Generated by Django 5.2 on 2025-07-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator')], default='operator', help_text='Role of the user in the system.', max_length=20),
        ),
    ]
