"""
Django settings for emergency_callback project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o%nh8zr%cgo+_e-dut@wzv^mqi=n3l0#(u-t0#ud^aj7oz%qp5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', 'callback.diyarbek.uz', 'localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'teams',
    'callbacks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'emergency_callback.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'emergency_callback.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'emergency_callback',
        'USER': 'postgres',
        'PASSWORD': '02052005',
        'HOST': 'localhost',
        'PORT': '5432',
        "OPTIONS": {
            "pool": {
                "min_size": 10,
                "max_size": 100,
                "timeout": 10,
            }
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

CELERY_BROKER_URL = 'redis://localhost:6379/2'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/2'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

AMBULANCE_CONFIG = {
    'AMI_HOST': '172.16.95.250',  # Changed from '127.0.0.1'
    'AMI_PORT': 5038,
    'AMI_USERNAME': 'srtapi_amidefault',  # Changed from 'astmanager'
    'AMI_SECRET': 'amidefault',  # Changed from '02052005'
    'CALLER_ID' : '"Ambulance Service" <781138081>',
    'MAX_CHANNELS': 2,
    'OPERATOR_QUEUE': '777',  # Changed from 'OPERATOR_EXTENSION': '101'
    'CALL_TIMEOUT': 60,  # seconds
    'AUDIO_FILES': {
        'rating_request': 'ambulance-rating-request',
        'rating_thankyou': 'ambulance-rating-thankyou',
        'rating_invalid': 'ambulance-rating-invalid',
        'rating_failed': 'ambulance-rating-invalid',
    },

    'RATING_RETRY_LIMIT': 3,  # How many times to retry getting a rating
    'RATING_TIMEOUT': 10,     # How long to wait for rating input (seconds)
    'ADDITIONAL_TIMEOUT': 10, # How long to wait for additional questions input

    'MAX_RECONNECT_ATTEMPTS': 5,  # Number of reconnection attempts
    'RECONNECT_DELAY': 5,  # Seconds between reconnection attempts
    'PING_INTERVAL': 30,  # Seconds between health check pings
    'CONNECTION_TIMEOUT': 10,  # Timeout for initial connection

    # Health monitoring
    'HEALTH_CHECK_ENABLED': True,
    'HEALTH_CHECK_INTERVAL': 60,  # Run health check every 60 seconds
}

LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'callbacks:dashboard'
LOGOUT_REDIRECT_URL = 'users:login'

CELERY_BEAT_SCHEDULE = {
    'ambulance-health-check': {
        'task': 'your_app.tasks.check_ambulance_system_health',
        'schedule': 60.0,  # Every minute
    },
    'cleanup-stale-calls': {
        'task': 'your_app.tasks.cleanup_stale_calls',
        'schedule': crontab(minute='*/15'),  # Every 15 minutes
    },
}