# Generated by Django 5.2 on 2025-06-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dialing', 'Dialing'), ('connecting', 'Connecting'), ('answered', 'Answered'), ('waiting_rating', 'Waiting Rating'), ('waiting_additional', 'Waiting Additional'), ('transferring', 'Transferring'), ('completed', 'Completed'), ('no_rating', 'No Rating Given'), ('transferred', 'Transferred'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('call_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('uniqueid', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call_started_at', models.DateTimeField(blank=True, null=True)),
                ('call_ended_at', models.DateTimeField(blank=True, null=True)),
                ('call_duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('transferred', models.BooleanField(default=False)),
                ('additional_questions', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
