# Generated by Django 5.2 on 2025-06-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackrequest',
            name='call_duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dialing', 'Dialing'), ('connecting', 'Connecting'), ('answered', 'Answered'), ('waiting_rating', 'Waiting Rating'), ('waiting_additional', 'Waiting Additional'), ('transferring', 'Transferring'), ('completed', 'Completed'), ('no_rating', 'No Rating Given'), ('transferred', 'Transferred'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
