# Generated by Django 5.2 on 2025-07-25 09:55

import callbacks.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0002_initial'),
        ('teams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callbackrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос обратного вызова', 'verbose_name_plural': 'Запросы обратного вызова'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Оценка вызова', 'verbose_name_plural': 'Оценки вызовов'},
        ),
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, help_text='Дополнительный комментарий к оценке (необязательно)', max_length=500, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='additional_questions',
            field=models.BooleanField(blank=True, help_text='Были ли заданы дополнительные вопросы', null=True, verbose_name='Дополнительные вопросы'),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='call_duration',
            field=models.IntegerField(blank=True, help_text='Длительность вызова в секундах', null=True, verbose_name='Длительность вызова'),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='call_ended_at',
            field=models.DateTimeField(blank=True, help_text='Когда закончился звонок', null=True, verbose_name='Время окончания звонка'),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='call_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='Уникальный идентификатор вызова', null=True, unique=True, verbose_name='ID вызова'),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='call_started_at',
            field=models.DateTimeField(blank=True, help_text='Когда начался звонок', null=True, verbose_name='Время начала звонка'),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='channel',
            field=models.CharField(blank=True, help_text='Канал телефонной системы', max_length=100, null=True, verbose_name='Канал связи'),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Когда был создан запрос на обратный вызов', verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='error_message',
            field=models.TextField(blank=True, help_text='Описание ошибки, если вызов не удался', null=True, verbose_name='Сообщение об ошибке'),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='phone_number',
            field=models.CharField(help_text='Номер телефона в международном формате', max_length=20, validators=[callbacks.models.validate_phone_number], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='requested_by',
            field=models.ForeignKey(help_text='Пользователь, который создал запрос на обратный вызов', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто запросил'),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('dialing', 'Набирается'), ('connecting', 'Соединение'), ('answered', 'Отвечен'), ('waiting_rating', 'Ожидание оценки'), ('waiting_additional', 'Ожидание дополнительной информации'), ('transferring', 'Перевод'), ('completed', 'Завершен успешно'), ('no_rating', 'Без оценки'), ('transferred', 'Переведен оператору'), ('failed', 'Неудачный вызов')], default='pending', help_text='Текущее состояние обратного вызова', max_length=20, verbose_name='Статус вызова'),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='team',
            field=models.ForeignKey(help_text='Бригада экстренного реагирования', on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Бригада'),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='transferred',
            field=models.BooleanField(default=False, help_text='Был ли вызов переведен оператору', verbose_name='Переведен'),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='uniqueid',
            field=models.CharField(blank=True, help_text='Внутренний идентификатор телефонной системы', max_length=100, null=True, verbose_name='Уникальный ID системы'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='callback_request',
            field=models.OneToOneField(help_text='Связанный запрос обратного вызова', on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='callbacks.callbackrequest', verbose_name='Запрос обратного вызова'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='Дата постановки оценки', verbose_name='Дата оценки'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='phone_number',
            field=models.CharField(help_text='Номер телефона (копия для анализа)', max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 - Очень плохо'), (2, '2 - Плохо'), (3, '3 - Удовлетворительно'), (4, '4 - Хорошо'), (5, '5 - Отлично')], help_text='Оценка качества обслуживания от 1 до 5', verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='team',
            field=models.ForeignKey(help_text='Бригада (копия для анализа)', on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Бригада'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Когда была поставлена оценка', verbose_name='Время оценки'),
        ),
        migrations.AddIndex(
            model_name='callbackrequest',
            index=models.Index(fields=['status'], name='callbacks_c_status_9887d8_idx'),
        ),
        migrations.AddIndex(
            model_name='callbackrequest',
            index=models.Index(fields=['created_at'], name='callbacks_c_created_0d12d7_idx'),
        ),
        migrations.AddIndex(
            model_name='callbackrequest',
            index=models.Index(fields=['phone_number'], name='callbacks_c_phone_n_9e62b5_idx'),
        ),
        migrations.AddIndex(
            model_name='callbackrequest',
            index=models.Index(fields=['team'], name='callbacks_c_team_id_788124_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rating'], name='callbacks_r_rating_9e9373_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['date'], name='callbacks_r_date_d75927_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['team'], name='callbacks_r_team_id_a472e6_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['timestamp'], name='callbacks_r_timesta_1e6224_idx'),
        ),
    ]
