# Generated by Django 5.2 on 2025-06-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0003_callbackrequest_call_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackrequest',
            name='max_retries_reached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='original_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dialing', 'Dialing'), ('connecting', 'Connecting'), ('answered', 'Answered'), ('waiting_rating', 'Waiting Rating'), ('waiting_additional', 'Waiting Additional'), ('transferring', 'Transferring'), ('completed', 'Completed'), ('no_rating', 'No Rating Given'), ('transferred', 'Transferred'), ('failed', 'Failed'), ('retry_scheduled', 'Retry Scheduled')], default='pending', max_length=20),
        ),
    ]
