# Generated by Django 5.2 on 2025-11-03 10:07

import uuid
from django.conf import settings
from django.db import migrations, models


def generate_vote_uuids(apps, schema_editor):
    CallbackRequest = apps.get_model('callbacks', 'CallbackRequest')
    for callback in CallbackRequest.objects.all():
        callback.vote_uuid = uuid.uuid4()
        callback.save(update_fields=['vote_uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('callbacks', '0003_alter_callbackrequest_options_alter_rating_options_and_more'),
        ('teams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add other fields first
        migrations.AddField(
            model_name='callbackrequest',
            name='sms_sent',
            field=models.BooleanField(default=False, help_text='Было ли отправлено SMS с просьбой оценить',
                                      verbose_name='SMS отправлено'),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, help_text='Когда было отправлено SMS', null=True,
                                       verbose_name='Время отправки SMS'),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='voted_via_sms',
            field=models.BooleanField(default=False, help_text='Пользователь проголосовал через SMS ссылку',
                                      verbose_name='Проголосовал через SMS'),
        ),

        # Add vote_uuid as nullable first
        migrations.AddField(
            model_name='callbackrequest',
            name='vote_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, blank=True,
                                   help_text='Уникальный идентификатор для SMS голосования',
                                   verbose_name='UUID для голосования'),
        ),

        # Generate UUIDs for existing records
        migrations.RunPython(generate_vote_uuids, migrations.RunPython.noop),

        # Make it unique and non-nullable
        migrations.AlterField(
            model_name='callbackrequest',
            name='vote_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True,
                                   help_text='Уникальный идентификатор для SMS голосования',
                                   verbose_name='UUID для голосования'),
        ),

        # Add index
        migrations.AddIndex(
            model_name='callbackrequest',
            index=models.Index(fields=['vote_uuid'], name='callbacks_c_vote_uu_ea1a5d_idx'),
        ),
    ]