# Generated by Django 5.2 on 2025-06-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0004_callbackrequest_max_retries_reached_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callbackrequest',
            name='max_retries_reached',
        ),
        migrations.RemoveField(
            model_name='callbackrequest',
            name='next_retry_at',
        ),
        migrations.RemoveField(
            model_name='callbackrequest',
            name='original_created_at',
        ),
        migrations.RemoveField(
            model_name='callbackrequest',
            name='retry_count',
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dialing', 'Dialing'), ('connecting', 'Connecting'), ('answered', 'Answered'), ('waiting_rating', 'Waiting Rating'), ('waiting_additional', 'Waiting Additional'), ('transferring', 'Transferring'), ('completed', 'Completed'), ('no_rating', 'No Rating Given'), ('transferred', 'Transferred'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
